// Generated by commsdsl2comms v3.3.1

/// @file
/// @brief Contains definition of <b>"CONNECT"</b> message and its fields.

#pragma once

#include <cstdint>
#include <tuple>
#include "comms/MessageBase.h"
#include "comms/field/Bitfield.h"
#include "comms/field/BitmaskValue.h"
#include "comms/field/IntValue.h"
#include "comms/field/Optional.h"
#include "comms/options.h"
#include "mqtt5/MsgId.h"
#include "mqtt5/field/BinData.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/PropertiesList.h"
#include "mqtt5/field/ProtocolName.h"
#include "mqtt5/field/Qos.h"
#include "mqtt5/field/String.h"
#include "mqtt5/message/ConnectCommon.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace message
{

/// @brief Fields of @ref Connect.
/// @tparam TOpt Extra options
/// @see @ref Connect
/// @headerfile "mqtt5/message/Connect.h"
template <typename TOpt = mqtt5::options::DefaultOptions>
struct ConnectFields
{
    /// @brief Definition of <b>"Protocol Name"</b> field.
    using ProtocolName =
        mqtt5::field::ProtocolName<
            TOpt
        >;
    
    /// @brief Definition of <b>"Protocol Version"</b> field.
    struct ProtocolVersion : public
        comms::field::IntValue<
            mqtt5::field::FieldBase<>,
            std::uint8_t,
            comms::option::def::DefaultNumValue<5>,
            comms::option::def::ValidNumValue<5>
        >
    {
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::ProtocolVersionCommon::name();
        }
        
    };
    
    /// @brief Scope for all the member fields of @ref Flags bitfield.
    struct FlagsMembers
    {
        /// @brief Definition of <b>""</b> field.
        class Low : public
            comms::field::BitmaskValue<
                mqtt5::field::FieldBase<>,
                comms::option::def::FixedBitLength<3U>,
                comms::option::def::BitmaskReservedBits<0x1U, 0x0U>
            >
        {
            using Base = 
                comms::field::BitmaskValue<
                    mqtt5::field::FieldBase<>,
                    comms::option::def::FixedBitLength<3U>,
                    comms::option::def::BitmaskReservedBits<0x1U, 0x0U>
                >;
        public:
            /// @brief Provide names for internal bits.
            /// @details See definition of @b COMMS_BITMASK_BITS macro
            ///     related to @b comms::field::BitmaskValue class from COMMS library
            ///     for details.
            ///
            ///      The generated enum values:
            ///      @li @b BitIdx_cleanStart.
            ///      @li @b BitIdx_willFlag.
            COMMS_BITMASK_BITS(
                cleanStart=1,
                willFlag=2
            );
            
            /// @brief Generates independent access functions for internal bits.
            /// @details See definition of @b COMMS_BITMASK_BITS_ACCESS macro
            ///     related to @b comms::field::BitmaskValue class from COMMS library
            ///     for details.
            ///
            ///     The generated access functions are:
            ///      @li @b getBitValue_cleanStart() and @b setBitValue_cleanStart().
            ///      @li @b getBitValue_willFlag() and @b setBitValue_willFlag().
            COMMS_BITMASK_BITS_ACCESS(
                cleanStart,
                willFlag
            );
            
            /// @brief Name of the field.
            static const char* name()
            {
                return mqtt5::message::ConnectFieldsCommon::FlagsMembersCommon::LowCommon::name();
            }
            
            /// @brief Retrieve name of the bit.
            static const char* bitName(BitIdx idx)
            {
                return
                    mqtt5::message::ConnectFieldsCommon::FlagsMembersCommon::LowCommon::bitName(
                        static_cast<std::size_t>(idx));
            }
            
        };
        
        /// @brief Definition of <b>"Will QoS"</b> field.
        struct WillQos : public
            mqtt5::field::Qos<
                TOpt,
                comms::option::def::FixedBitLength<2U>
            >
        {
            /// @brief Name of the field.
            static const char* name()
            {
                return mqtt5::message::ConnectFieldsCommon::FlagsMembersCommon::WillQosCommon::name();
            }
            
        };
        
        /// @brief Definition of <b>""</b> field.
        class High : public
            comms::field::BitmaskValue<
                mqtt5::field::FieldBase<>,
                comms::option::def::FixedBitLength<3U>
            >
        {
            using Base = 
                comms::field::BitmaskValue<
                    mqtt5::field::FieldBase<>,
                    comms::option::def::FixedBitLength<3U>
                >;
        public:
            /// @brief Provides names and generates access functions for internal bits.
            /// @details See definition of @b COMMS_BITMASK_BITS_SEQ macro
            ///     related to @b comms::field::BitmaskValue class from COMMS library
            ///     for details.
            ///
            ///      The generated enum values and functions are:
            ///      @li @b BitIdx_willRetain, @b getBitValue_willRetain() and @b setBitValue_willRetain().
            ///      @li @b BitIdx_passwordFlag, @b getBitValue_passwordFlag() and @b setBitValue_passwordFlag().
            ///      @li @b BitIdx_userNameFlag, @b getBitValue_userNameFlag() and @b setBitValue_userNameFlag().
            COMMS_BITMASK_BITS_SEQ(
                willRetain,
                passwordFlag,
                userNameFlag
            );
            
            /// @brief Name of the field.
            static const char* name()
            {
                return mqtt5::message::ConnectFieldsCommon::FlagsMembersCommon::HighCommon::name();
            }
            
            /// @brief Retrieve name of the bit.
            static const char* bitName(BitIdx idx)
            {
                return
                    mqtt5::message::ConnectFieldsCommon::FlagsMembersCommon::HighCommon::bitName(
                        static_cast<std::size_t>(idx));
            }
            
        };
        
        /// @brief All members bundled in @b std::tuple.
        using All =
            std::tuple<
               Low,
               WillQos,
               High
            >;
    };
    
    /// @brief Definition of <b>"Connect Flags"</b> field.
    class Flags : public
        comms::field::Bitfield<
            mqtt5::field::FieldBase<>,
            typename FlagsMembers::All
        >
    {
        using Base = 
            comms::field::Bitfield<
                mqtt5::field::FieldBase<>,
                typename FlagsMembers::All
            >;
    public:
        /// @brief Allow access to internal fields.
        /// @details See definition of @b COMMS_FIELD_MEMBERS_NAMES macro
        ///     related to @b comms::field::Bitfield class from COMMS library
        ///     for details.
        ///
        ///     The generated access functions are:
        ///     @li @b Field_low @b field_low() -
        ///         for FlagsMembers::Low member field.
        ///     @li @b Field_willQos @b field_willQos() -
        ///         for FlagsMembers::WillQos member field.
        ///     @li @b Field_high @b field_high() -
        ///         for FlagsMembers::High member field.
        COMMS_FIELD_MEMBERS_NAMES(
            low,
            willQos,
            high
        );
        
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::FlagsCommon::name();
        }
        
    };
    
    /// @brief Definition of <b>"Keep Alive"</b> field.
    struct KeepAlive : public
        comms::field::IntValue<
            mqtt5::field::FieldBase<>,
            std::uint16_t
        >
    {
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::KeepAliveCommon::name();
        }
        
    };
    
    /// @brief Definition of <b>"Properties"</b> field.
    using Properties =
        mqtt5::field::PropertiesList<
            TOpt
        >;
    
    /// @brief Definition of <b>"Client ID"</b> field.
    struct ClientId : public
        mqtt5::field::String<
            TOpt
        >
    {
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::ClientIdCommon::name();
        }
        
    };
    
    /// @brief Scope for all the member fields of @ref WillProperties optional.
    struct WillPropertiesMembers
    {
        /// @brief Definition of <b>"Will Properties"</b> field.
        struct Properties : public
            mqtt5::field::PropertiesList<
                TOpt
            >
        {
            /// @brief Name of the field.
            static const char* name()
            {
                return mqtt5::message::ConnectFieldsCommon::WillPropertiesMembersCommon::PropertiesCommon::name();
            }
            
        };
        
    };
    
    /// @brief Definition of <b>"Will Properties"</b> field.
    struct WillProperties : public
        comms::field::Optional<
            typename WillPropertiesMembers::Properties,
            comms::option::def::MissingByDefault
        >
    {
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::WillPropertiesCommon::name();
        }
        
    };
    
    /// @brief Scope for all the member fields of @ref WillTopic optional.
    struct WillTopicMembers
    {
        /// @brief Definition of <b>"Will Topic"</b> field.
        struct Topic : public
            mqtt5::field::String<
                TOpt
            >
        {
            /// @brief Name of the field.
            static const char* name()
            {
                return mqtt5::message::ConnectFieldsCommon::WillTopicMembersCommon::TopicCommon::name();
            }
            
        };
        
    };
    
    /// @brief Definition of <b>"Will Topic"</b> field.
    struct WillTopic : public
        comms::field::Optional<
            typename WillTopicMembers::Topic,
            comms::option::def::MissingByDefault
        >
    {
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::WillTopicCommon::name();
        }
        
    };
    
    /// @brief Scope for all the member fields of @ref WillMessage optional.
    struct WillMessageMembers
    {
        /// @brief Definition of <b>"Will Message"</b> field.
        struct WillMessage : public
            mqtt5::field::BinData<
                TOpt
            >
        {
            /// @brief Name of the field.
            static const char* name()
            {
                return mqtt5::message::ConnectFieldsCommon::WillMessageMembersCommon::WillMessageCommon::name();
            }
            
        };
        
    };
    
    /// @brief Definition of <b>"Will Message"</b> field.
    struct WillMessage : public
        comms::field::Optional<
            typename WillMessageMembers::WillMessage,
            comms::option::def::MissingByDefault
        >
    {
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::WillMessageCommon::name();
        }
        
    };
    
    /// @brief Scope for all the member fields of @ref UserName optional.
    struct UserNameMembers
    {
        /// @brief Definition of <b>"User Name"</b> field.
        struct UserName : public
            mqtt5::field::String<
                TOpt
            >
        {
            /// @brief Name of the field.
            static const char* name()
            {
                return mqtt5::message::ConnectFieldsCommon::UserNameMembersCommon::UserNameCommon::name();
            }
            
        };
        
    };
    
    /// @brief Definition of <b>"User Name"</b> field.
    struct UserName : public
        comms::field::Optional<
            typename UserNameMembers::UserName,
            comms::option::def::MissingByDefault
        >
    {
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::UserNameCommon::name();
        }
        
    };
    
    /// @brief Scope for all the member fields of @ref Password optional.
    struct PasswordMembers
    {
        /// @brief Definition of <b>"Password"</b> field.
        struct Password : public
            mqtt5::field::BinData<
                TOpt
            >
        {
            /// @brief Name of the field.
            static const char* name()
            {
                return mqtt5::message::ConnectFieldsCommon::PasswordMembersCommon::PasswordCommon::name();
            }
            
        };
        
    };
    
    /// @brief Definition of <b>"Password"</b> field.
    struct Password : public
        comms::field::Optional<
            typename PasswordMembers::Password,
            comms::option::def::MissingByDefault
        >
    {
        /// @brief Name of the field.
        static const char* name()
        {
            return mqtt5::message::ConnectFieldsCommon::PasswordCommon::name();
        }
        
    };
    
    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        ProtocolName,
        ProtocolVersion,
        Flags,
        KeepAlive,
        Properties,
        ClientId,
        WillProperties,
        WillTopic,
        WillMessage,
        UserName,
        Password
    >;
};

/// @brief Definition of <b>"CONNECT"</b> message class.
/// @details
///     See @ref ConnectFields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile "mqtt5/message/Connect.h"
template <typename TMsgBase, typename TOpt = mqtt5::options::DefaultOptions>
class Connect : public
    comms::MessageBase<
        TMsgBase,
        typename TOpt::message::Connect,
        comms::option::def::StaticNumIdImpl<mqtt5::MsgId_Connect>,
        comms::option::def::FieldsImpl<typename ConnectFields<TOpt>::All>,
        comms::option::def::MsgType<Connect<TMsgBase, TOpt> >,
        comms::option::def::HasName,
        comms::option::def::HasCustomRefresh
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            typename TOpt::message::Connect,
            comms::option::def::StaticNumIdImpl<mqtt5::MsgId_Connect>,
            comms::option::def::FieldsImpl<typename ConnectFields<TOpt>::All>,
            comms::option::def::MsgType<Connect<TMsgBase, TOpt> >,
            comms::option::def::HasName,
            comms::option::def::HasCustomRefresh
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated types and functions are:
    ///     @li @b Field_protocolName type and @b field_protocolName() fuction
    ///         for @ref ConnectFields::ProtocolName field.
    ///     @li @b Field_protocolVersion type and @b field_protocolVersion() fuction
    ///         for @ref ConnectFields::ProtocolVersion field.
    ///     @li @b Field_flags type and @b field_flags() fuction
    ///         for @ref ConnectFields::Flags field.
    ///     @li @b Field_keepAlive type and @b field_keepAlive() fuction
    ///         for @ref ConnectFields::KeepAlive field.
    ///     @li @b Field_properties type and @b field_properties() fuction
    ///         for @ref ConnectFields::Properties field.
    ///     @li @b Field_clientId type and @b field_clientId() fuction
    ///         for @ref ConnectFields::ClientId field.
    ///     @li @b Field_willProperties type and @b field_willProperties() fuction
    ///         for @ref ConnectFields::WillProperties field.
    ///     @li @b Field_willTopic type and @b field_willTopic() fuction
    ///         for @ref ConnectFields::WillTopic field.
    ///     @li @b Field_willMessage type and @b field_willMessage() fuction
    ///         for @ref ConnectFields::WillMessage field.
    ///     @li @b Field_userName type and @b field_userName() fuction
    ///         for @ref ConnectFields::UserName field.
    ///     @li @b Field_password type and @b field_password() fuction
    ///         for @ref ConnectFields::Password field.
    COMMS_MSG_FIELDS_NAMES(
        protocolName,
        protocolVersion,
        flags,
        keepAlive,
        properties,
        clientId,
        willProperties,
        willTopic,
        willMessage,
        userName,
        password
    );
    
    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static_assert(MsgMinLen == 9U, "Unexpected min serialisation length");
    
    /// @brief Name of the message.
    static const char* doName()
    {
        return mqtt5::message::ConnectCommon::name();
    }
    
    /// @brief Custom read functionality
    template <typename TIter>
    comms::ErrorStatus doRead(TIter& iter, std::size_t len)
    {
        auto es = Base::template doReadUntilAndUpdateLen<FieldIdx_clientId>(iter, len);
        if (es != comms::ErrorStatus::Success) {
            return es;
        }
        
        doRefresh();
        return Base::template doReadFrom<FieldIdx_clientId>(iter, len);
    }
    
    /// @brief Updated validity check
    bool doValid() const
    {
        if ((!Base::doValid()) || (!Base::flagsZeroed())) {
            return false;
        }
        
        return 
            (!field_flags().field_high().getBitValue_passwordFlag()) ||
            (field_flags().field_high().getBitValue_userNameFlag());
    }
    
    /// @brief Custom refresh functionality
    bool doRefresh()
    {
        bool updated = Base::doRefresh();
        updated = refresh_willProperties() || updated;
        updated = refresh_willTopic() || updated;
        updated = refresh_willMessage() || updated;
        updated = refresh_userName() || updated;
        updated = refresh_password() || updated;
        return updated;
    }
    
    
private:
    template <typename TOptField>
    static bool refreshOptionalField(bool exists, TOptField& optField)
    {
        auto mode = comms::field::OptionalMode::Missing;
        if (exists) {
            mode = comms::field::OptionalMode::Exists;
        }
        
        if (optField.getMode() == mode) {
            return false;
        }
        
        optField.setMode(mode);
        return true;
    }
    
    bool refresh_willProperties()
    {
        return refreshOptionalField(field_flags().field_low().getBitValue_willFlag(), field_willProperties());
    }
    
    bool refresh_willTopic()
    {
        return refreshOptionalField(field_flags().field_low().getBitValue_willFlag(), field_willTopic());
    }
    
    bool refresh_willMessage()
    {
        return refreshOptionalField(field_flags().field_low().getBitValue_willFlag(), field_willMessage());
    }
    
    bool refresh_userName()
    {
        return refreshOptionalField(field_flags().field_high().getBitValue_userNameFlag(), field_userName());
    }
    
    bool refresh_password()
    {
        return refreshOptionalField(field_flags().field_high().getBitValue_passwordFlag(), field_password());
    }
    
    
    
};

} // namespace message

} // namespace mqtt5


