// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Pingreq message and its fields.

#pragma once

namespace mqtt5
{

namespace message
{


/// @brief Common types and functions of 
///     @ref mqtt5::message::Pingreq message.
struct PingreqCommon
{
    /// @brief Name of the @ref mqtt5::message::Pingreq message.
    static const char* name()
    {
        return "PINGREQ";
    }
    
};

} // namespace message

} // namespace mqtt5



