// Generated by commsdsl2comms v3.6.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::message::Pingresp message and its fields.

#pragma once

namespace mqtt5
{

namespace message
{

/// @brief Common types and functions of 
///     @ref mqtt5::message::Pingresp message.
/// @see mqtt5::message::Pingresp
struct PingrespCommon
{
    /// @brief Name of the @ref mqtt5::message::Pingresp message.
    static const char* name()
    {
        return "PINGRESP";
    }
    
};

} // namespace message

} // namespace mqtt5


