// Generated by commsdsl2comms v5.1.2

/// @file
/// @brief Contains definition of <b>"VarLenInt"</b> field.

#pragma once

#include <cstdint>
#include "cc_mqtt5/field/FieldBase.h"
#include "cc_mqtt5/field/VarLenIntCommon.h"
#include "cc_mqtt5/options/DefaultOptions.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"

namespace cc_mqtt5
{

namespace field
{

/// @brief Definition of <b>"VarLenInt"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = cc_mqtt5::options::DefaultOptions, typename... TExtraOpts>
class VarLenInt : public
    comms::field::IntValue<
        cc_mqtt5::field::FieldBase<comms::option::def::LittleEndian>,
        std::uint32_t,
        TExtraOpts...,
        comms::option::def::VarLength<1U, 4U>
    >
{
    using Base =
        comms::field::IntValue<
            cc_mqtt5::field::FieldBase<comms::option::def::LittleEndian>,
            std::uint32_t,
            TExtraOpts...,
            comms::option::def::VarLength<1U, 4U>
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;

    /// @brief Compile time detection of special values presence.
    static constexpr bool hasSpecials()
    {
        return cc_mqtt5::field::VarLenIntCommon::hasSpecials();
    }

    /// @brief Name of the field.
    static const char* name()
    {
        return cc_mqtt5::field::VarLenIntCommon::name();
    }
};

} // namespace field

} // namespace cc_mqtt5
