// Generated by commsdsl2comms v6.2.4

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt5::message::Auth message and its fields.

#pragma once

namespace cc_mqtt5
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqtt5::message::Auth message.
/// @see cc_mqtt5::message::AuthFields
struct AuthFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_mqtt5::message::AuthFields::ReasonCode field.
    struct ReasonCodeCommon
    {
        /// @brief Name of the @ref cc_mqtt5::message::AuthFields::ReasonCode field.
        static const char* name()
        {
            return "Reason Code";
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_mqtt5::message::AuthFields::Properties field.
    struct PropertiesCommon
    {
        /// @brief Name of the @ref cc_mqtt5::message::AuthFields::Properties field.
        static const char* name()
        {
            return "Properties";
        }
    };
};

/// @brief Common types and functions of 
///     @ref cc_mqtt5::message::Auth message.
struct AuthCommon
{
    /// @brief Name of the @ref cc_mqtt5::message::Auth message.
    static const char* name()
    {
        return "AUTH";
    }
};

} // namespace message

} // namespace cc_mqtt5
