// Generated by commsdsl2comms v6.2.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt5::message::Disconnect message and its fields.

#pragma once

#include "cc_mqtt5/field/PropertiesListCommon.h"
#include "cc_mqtt5/field/ReasonCodeCommon.h"

namespace cc_mqtt5
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqtt5::message::Disconnect message.
/// @see cc_mqtt5::message::DisconnectFields
struct DisconnectFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_mqtt5::message::DisconnectFields::ReasonCode field.
    using ReasonCodeCommon = cc_mqtt5::field::ReasonCodeCommon;

    /// @brief Common definitions of the member fields of
    ///     @ref cc_mqtt5::message::DisconnectFields::PropertiesList field.
    using PropertiesListMembersCommon = cc_mqtt5::field::PropertiesListMembersCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqtt5::message::DisconnectFields::PropertiesList field.
    using PropertiesListCommon = cc_mqtt5::field::PropertiesListCommon;
};

/// @brief Common types and functions of 
///     @ref cc_mqtt5::message::Disconnect message.
struct DisconnectCommon
{
    /// @brief Name of the @ref cc_mqtt5::message::Disconnect message.
    static const char* name()
    {
        return "DISCONNECT";
    }
};

} // namespace message

} // namespace cc_mqtt5
