// Generated by commsdsl2comms v7.1.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt5::message::Pubcomp message and its fields.

#pragma once

#include "cc_mqtt5/field/PacketIdCommon.h"

namespace cc_mqtt5
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqtt5::message::Pubcomp message.
/// @see cc_mqtt5::message::PubcompFields
struct PubcompFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_mqtt5::message::PubcompFields::PacketId field.
    using PacketIdCommon = cc_mqtt5::field::PacketIdCommon;

    /// @brief Common types and functions for
    ///     @ref cc_mqtt5::message::PubcompFields::ReasonCode field.
    struct ReasonCodeCommon
    {
        /// @brief Name of the @ref cc_mqtt5::message::PubcompFields::ReasonCode field.
        static const char* name()
        {
            return "Reason Code";
        }
    };

    /// @brief Common types and functions for
    ///     @ref cc_mqtt5::message::PubcompFields::Properties field.
    struct PropertiesCommon
    {
        /// @brief Name of the @ref cc_mqtt5::message::PubcompFields::Properties field.
        static const char* name()
        {
            return "Properties";
        }
    };
};

/// @brief Common types and functions of 
///     @ref cc_mqtt5::message::Pubcomp message.
struct PubcompCommon
{
    /// @brief Name of the @ref cc_mqtt5::message::Pubcomp message.
    static const char* name()
    {
        return "PUBCOMP";
    }
};

} // namespace message

} // namespace cc_mqtt5
