// Generated by commsdsl2comms v3.6.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::ProtocolName field.

#pragma once

namespace mqtt5
{

namespace field
{

/// @brief Scope for all the common definitions of the
///     @ref mqtt5::field::ProtocolName field.
struct ProtocolNameCommon
{
    /// @brief Name of the @ref mqtt5::field::ProtocolName field.
    static const char* name()
    {
        return "Protocol Name";
    }
    
};


} // namespace field

} // namespace mqtt5


