// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::ProtocolName field.

#pragma once

namespace mqtt5
{

namespace field
{

/// @brief Common types and functions for
///     @ref mqtt5::field::ProtocolName field.
struct ProtocolNameCommon
{
    /// @brief Name of the @ref mqtt5::field::ProtocolName field.
    static const char* name()
    {
        return "Protocol Name";
    }
};

} // namespace field

} // namespace mqtt5
