// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::Topic field.

#pragma once

#include "mqtt5/field/StringCommon.h"

namespace mqtt5
{

namespace field
{


/// @brief Common types and functions for
///     @ref mqtt5::field::Topic field.
struct TopicCommon : public mqtt5::field::StringCommon
{
    /// @brief Name of the @ref mqtt5::field::Topic field.
    static const char* name()
    {
        return "Topic";
    }
    
};

} // namespace field

} // namespace mqtt5

