// Generated by commsdsl2comms v4.0.0

/// @file
/// @brief Contains definition of <b>"VarLenInt"</b> field.

#pragma once

#include <cstdint>
#include "comms/field/IntValue.h"
#include "comms/options.h"
#include "mqtt5/field/FieldBase.h"
#include "mqtt5/field/VarLenIntCommon.h"
#include "mqtt5/options/DefaultOptions.h"

namespace mqtt5
{

namespace field
{


/// @brief Definition of <b>"VarLenInt"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = mqtt5::options::DefaultOptions, typename... TExtraOpts>
class VarLenInt : public
    comms::field::IntValue<
        mqtt5::field::FieldBase<comms::option::def::LittleEndian>,
        std::uint32_t,
        TExtraOpts...,
        comms::option::def::VarLength<1U, 4U>
    >
{
    using Base =
        comms::field::IntValue<
            mqtt5::field::FieldBase<comms::option::def::LittleEndian>,
            std::uint32_t,
            TExtraOpts...,
            comms::option::def::VarLength<1U, 4U>
        >;
public:
    /// @brief Re-definition of the value type.
    using ValueType = typename Base::ValueType;
    
    /// @brief Compile time detection of special values presence.
    static constexpr bool hasSpecials()
    {
        return mqtt5::field::VarLenIntCommon::hasSpecials();
    }
    
    
    /// @brief Name of the field.
    static const char* name()
    {
        return mqtt5::field::VarLenIntCommon::name();
    }
    

};


} // namespace field

} // namespace mqtt5

