// Generated by commsdsl2comms v3.6.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt5::field::VarLenInt field.

#pragma once

#include <cstdint>

namespace mqtt5
{

namespace field
{

/// @brief Common types and functions for
///     @ref mqtt5::field::VarLenInt field.
struct VarLenIntCommon
{
    /// @brief Re-definition of the value type used by
    ///     mqtt5::field::VarLenInt field.
    using ValueType = std::uint32_t;

    /// @brief Name of the @ref mqtt5::field::VarLenInt field.
    static const char* name()
    {
        return "VarLenInt";
    }
    
};

} // namespace field

} // namespace mqtt5


